language: python
cache: pip

matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8

git:
  depth: 1

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install flake8
  - pip install coveralls
  - pip install codecov

script:
#  - flake8 ./sd.py
#  - flake8 ./oe.py
  - pytest --cov=./

after_success:
  - codecov
  - coveralls
